### ISSUE TITLE
No module named 'data_loaders'

### ISSUE THREAD

**Issue by ZheChen1999** [ahmedhshahin/IPFSurv#1]
Could you please upload the data_loaders.py file? Or upload the complete project? Thanks!

**Comment by ahmedhshahin** [comment]
Hello,

Thanks for your question. I have added the dataloader file, but to get the data you will need to [register here](https://www.osicild.org/dr-about.html). You can apply the code to other datasets by providing a similar PyTorch dataloader. Please also note that the repository is still under construction, I will find some time soon to prepare the code.

Best,
Ahmed

**Comment by ZheChen1999** [comment]
Thanks, I would like to confirm whether the data of drugs and DLCO used in your paper are your own clinical data, or are they already available in OSIC (but I don't see DLCO data in it).

**Comment by ahmedhshahin** [comment]
All the data used in the paper came from OSIC, including the clinical data. OSIC repository has CT images with corresponding clinical data.

**Comment by ZheChen1999** [comment]
https://www.kaggle.com/competitions/osic-pulmonary-fibrosis-progression/data   Thanks,  I found kaggle has not the DLCO clinical data.

**Comment by ahmedhshahin** [comment]
The kaggle data is just a subset of the OSIC data for that kaggle challenge. The full osic repository includes more cases and more clinical information.

**Comment by ZheChen1999** [comment]
Do you have a Google disk link to the full OSIC dataset? I can't join the OSIC Menber so that I can not download the dataset.  Thanks!
