### ISSUE TITLE
How to obtain .txt files

### ISSUE THREAD

**Issue by CarlosHernandezP** [ahmedhshahin/IPFSurv#2]
I am interested in replicating your approach for imputing missing values for my own research. 

On the file [`custom_transforms.py`](https://github.com/ahmedhshahin/IPFSurv/blob/main/custom_transforms.py) we can read these two lines on 300 and 301:
```
        with open("phgen.txt","rb") as f: self.ph = pickle.load(f)
        with open("pxghgen.txt","rb") as f: self.pxgh = pickle.load(f)
```

I presume these values are `p(h)` and `p(x_i | h)` obtained through Expectation Maximization. I have found no reference on this repository on how to obtain these values. Is there any possibility that you could include this in your code?

**Comment by ahmedhshahin** [comment]
Hi Carlos!

Thanks for your interest in our work and sorry for the delayed response.
Your presumption is correct and I have uploaded the pickle files ([here](https://github.com/ahmedhshahin/IPFSurv/blob/ffdaba9b6af7eb0458638e9e39d53f80dbca4f52/phgen.txt) and [here](https://github.com/ahmedhshahin/IPFSurv/blob/ffdaba9b6af7eb0458638e9e39d53f80dbca4f52/pxghgen.txt)). However, these distributions are the ones fitted on our data, so you might want to re-fit the model on your data. In case you wanted to do this, I have uploaded [the training file](https://github.com/ahmedhshahin/IPFSurv/blob/main/impute_missing_data.py).

You might also want to go through the derivation in the appendix of the paper.
Please let me know if you have any issues or questions.

Thanks!
Ahmed
